# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Shared
    autoload :Security, 'open_api_sdk/models/shared/security.rb'
  end
end
