# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Shared
    autoload :Status, 'open_api_sdk/models/shared/status.rb'
    autoload :Images, 'open_api_sdk/models/shared/images.rb'
    autoload :Files, 'open_api_sdk/models/shared/files.rb'
    autoload :Gifs, 'open_api_sdk/models/shared/gifs.rb'
    autoload :Data, 'open_api_sdk/models/shared/data.rb'
    autoload :Outputs, 'open_api_sdk/models/shared/outputs.rb'
    autoload :RunUpdatesRequestBody, 'open_api_sdk/models/shared/runupdates_requestbody.rb'
    autoload :RunUpdatesResponse, 'open_api_sdk/models/shared/runupdates_response.rb'
    autoload :Security, 'open_api_sdk/models/shared/security.rb'
  end
end
