# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Webhooks
  

    class RunUpdatesRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :live_status, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('live_status') } }

      field :outputs, T::Array[::OpenApiSDK::Webhooks::Outputs], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('outputs') } }

      field :progress, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('progress') } }

      field :run_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('run_id') } }

      field :status, ::OpenApiSDK::Webhooks::Status, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Webhooks::Status, false) } }


      sig { params(live_status: ::String, outputs: T::Array[::OpenApiSDK::Webhooks::Outputs], progress: ::Float, run_id: ::String, status: ::OpenApiSDK::Webhooks::Status).void }
      def initialize(live_status: nil, outputs: nil, progress: nil, run_id: nil, status: nil)
        @live_status = live_status
        @outputs = outputs
        @progress = progress
        @run_id = run_id
        @status = status
      end
    end
  end
end
