# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  autoload :ComfyDeploy, 'open_api_sdk/comfydeploy'
  autoload :Shared, 'open_api_sdk/models/shared'
  autoload :Operations, 'open_api_sdk/models/operations'
  autoload :Run, 'open_api_sdk/run'
  autoload :Files, 'open_api_sdk/files'
  autoload :Workflows, 'open_api_sdk/workflows'
  autoload :Comfyui, 'open_api_sdk/comfyui'
  autoload :Machines, 'open_api_sdk/machines'
end

require_relative 'open_api_sdk/utils/t'
require_relative 'open_api_sdk/utils/utils'
require_relative 'open_api_sdk/utils/metadata_fields'
require_relative 'open_api_sdk/sdkconfiguration'
