workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    comfydeploy-api:
        inputs:
            - location: https://www.comfydeploy.com/api
#            - location: http://localhost:3010/api/openapi.json
        registry:
            location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/comfydeploy-api
targets:
    comfy-deploy:
        target: ruby
        source: comfydeploy-api
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/code-samples-ruby-comfy-deploy
