# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'sorbet-runtime'

module OpenApiSDK
  extend T::Sig
  class Files
    extend T::Sig


    sig { params(sdk_config: SDKConfiguration).void }
    def initialize(sdk_config)
      @sdk_configuration = sdk_config
    end


    sig { params(type: ::OpenApiSDK::Operations::Type, file_size: ::String, file_extension: T.nilable(::String)).returns(::OpenApiSDK::Operations::GetUploadUrlResponse) }
    def get_upload_url(type, file_size, file_extension = nil)
      # get_upload_url - Upload any files to the storage
      # Usually when you run something, you want to upload a file, image etc.
      request = ::OpenApiSDK::Operations::GetUploadUrlRequest.new(
        
        type: type,
        file_size: file_size,
        file_extension: file_extension
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = "#{base_url}/upload-url"
      headers = {}
      query_params = Utils.get_query_params(::OpenApiSDK::Operations::GetUploadUrlRequest, request)
      headers['Accept'] = 'application/json;q=1, text/plain;q=0'
      headers['user-agent'] = @sdk_configuration.user_agent

      r = @sdk_configuration.client.get(url) do |req|
        req.headers = headers
        req.params = query_params
        Utils.configure_request_security(req, @sdk_configuration.security) if !@sdk_configuration.nil? && !@sdk_configuration.security.nil?
      end

      content_type = r.headers.fetch('Content-Type', 'application/octet-stream')

      res = ::OpenApiSDK::Operations::GetUploadUrlResponse.new(
        status_code: r.status, content_type: content_type, raw_response: r
      )
      if r.status == 200
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Operations::GetUploadUrlResponseBody)
          res.two_hundred_application_json_object = out
        end
      elsif r.status == 401
        res.four_hundred_and_one_text_plain_res = r.env.response_body if Utils.match_content_type(content_type, 'text/plain')
      elsif r.status == 500
        if Utils.match_content_type(content_type, 'application/json')
          out = Utils.unmarshal_complex(r.env.response_body, ::OpenApiSDK::Operations::GetUploadUrlFilesResponseBody)
          res.five_hundred_application_json_object = out
        end
      end

      res
    end
  end
end
