# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Dependencies < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :comfyui, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('comfyui') } }

      field :custom_nodes, T::Hash[Symbol, ::OpenApiSDK::Operations::CustomNodes], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('custom_nodes') } }

      field :files, T::Hash[Symbol, T::Array[::OpenApiSDK::Operations::Files]], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('files') } }

      field :missing_nodes, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('missing_nodes') } }

      field :models, T::Hash[Symbol, T::Array[::OpenApiSDK::Operations::Models]], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('models') } }


      sig { params(comfyui: ::String, custom_nodes: T::Hash[Symbol, ::OpenApiSDK::Operations::CustomNodes], files: T::Hash[Symbol, T::Array[::OpenApiSDK::Operations::Files]], missing_nodes: T::Array[::String], models: T::Hash[Symbol, T::Array[::OpenApiSDK::Operations::Models]]).void }
      def initialize(comfyui: nil, custom_nodes: nil, files: nil, missing_nodes: nil, models: nil)
        @comfyui = comfyui
        @custom_nodes = custom_nodes
        @files = files
        @missing_nodes = missing_nodes
        @models = models
      end
    end
  end
end
