# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Environment
    class Environment < T::Enum
      enums do
        PRODUCTION = new('production')
        STAGING = new('staging')
      end
    end
  end
end
