# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class EventType < T::Enum
      enums do
        GPU_START = new('gpu_start')
        GPU_END = new('gpu_end')
      end
    end
  end
end
