# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Fields
    class Fields < T::Enum
      enums do
        FULL = new('full')
        MINIMAL = new('minimal')
      end
    end

  end
end
