# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetMachineMachineIdEventsRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :machine_id, ::String, { 'path_param': { 'field_name': 'machine_id', 'style': 'simple', 'explode': false } }

      field :status, ::OpenApiSDK::Operations::Status, { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': true } }

      field :limit, T.nilable(::Float), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }


      sig { params(machine_id: ::String, status: ::OpenApiSDK::Operations::Status, limit: T.nilable(::Float)).void }
      def initialize(machine_id: nil, status: nil, limit: nil)
        @machine_id = machine_id
        @status = status
        @limit = limit
      end
    end
  end
end
