# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetRunGpu < T::Enum
      enums do
        CPU = new('CPU')
        T4 = new('T4')
        L4 = new('L4')
        A10_G = new('A10G')
        L40_S = new('L40S')
        A100 = new('A100')
        A100_80_GB = new('A100-80GB')
        H100 = new('H100')
      end
    end
  end
end
