# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1WorkflowsRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :page, T.nilable(::String), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }

      field :page_size, T.nilable(::String), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }

      field :search, T.nilable(::String), { 'query_param': { 'field_name': 'search', 'style': 'form', 'explode': true } }


      sig { params(page: T.nilable(::String), page_size: T.nilable(::String), search: T.nilable(::String)).void }
      def initialize(page: nil, page_size: nil, search: nil)
        @page = page
        @page_size = page_size
        @search = search
      end
    end
  end
end
