# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Workflow not found
    class GetRunRunResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :code, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code') } }

      field :message, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('message') } }


      sig { params(code: ::String, message: ::String).void }
      def initialize(code: nil, message: nil)
        @code = code
        @message = message
      end
    end
  end
end
