# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Retrieve the output
    class GetUploadUrlResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :download_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('download_url') } }

      field :file_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_id') } }

      field :upload_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('upload_url') } }


      sig { params(download_url: ::String, file_id: ::String, upload_url: ::String).void }
      def initialize(download_url: nil, file_id: nil, upload_url: nil)
        @download_url = download_url
        @file_id = file_id
        @upload_url = upload_url
      end
    end
  end
end
