# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Specific workflow retrieved successfully
    class GetV1WorkflowsWorkflowIdOutputsResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :outputs, T::Array[::OpenApiSDK::Operations::GetV1WorkflowsWorkflowIdOutputsOutputs], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('outputs') } }

      field :total, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total') } }


      sig { params(outputs: T::Array[::OpenApiSDK::Operations::GetV1WorkflowsWorkflowIdOutputsOutputs], total: ::Float).void }
      def initialize(outputs: nil, total: nil)
        @outputs = outputs
        @total = total
      end
    end
  end
end
