# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetMachineMachineIdEventsMachineResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :cost, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cost') } }

      field :cost_item_title, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cost_item_title') } }

      field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :end_time, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('end_time') } }

      field :environment, ::OpenApiSDK::Operations::GetMachineMachineIdEventsEnvironment, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('environment'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::GetMachineMachineIdEventsEnvironment, false) } }

      field :gpu, ::OpenApiSDK::Operations::GetMachineMachineIdEventsGpu, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('gpu'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::GetMachineMachineIdEventsGpu, false) } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :machine_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machine_id') } }

      field :machine_version_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machine_version_id') } }

      field :modal_function_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modal_function_id') } }

      field :org_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('org_id') } }

      field :provider_type, ::OpenApiSDK::Operations::ProviderType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('providerType'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::ProviderType, false) } }

      field :session_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('session_id') } }

      field :session_timeout, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('session_timeout') } }

      field :start_time, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('start_time') } }

      field :tunnel_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tunnel_url') } }

      field :updated_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at') } }

      field :user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }

      field :ws_gpu, ::OpenApiSDK::Operations::WsGpu, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ws_gpu'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::WsGpu, false) } }


      sig { params(cost: ::Float, cost_item_title: ::String, created_at: ::String, end_time: ::String, environment: ::OpenApiSDK::Operations::GetMachineMachineIdEventsEnvironment, gpu: ::OpenApiSDK::Operations::GetMachineMachineIdEventsGpu, id: ::String, machine_id: ::String, machine_version_id: ::String, modal_function_id: ::String, org_id: ::String, provider_type: ::OpenApiSDK::Operations::ProviderType, session_id: ::String, session_timeout: ::Float, start_time: ::String, tunnel_url: ::String, updated_at: ::String, user_id: ::String, ws_gpu: ::OpenApiSDK::Operations::WsGpu).void }
      def initialize(cost: nil, cost_item_title: nil, created_at: nil, end_time: nil, environment: nil, gpu: nil, id: nil, machine_id: nil, machine_version_id: nil, modal_function_id: nil, org_id: nil, provider_type: nil, session_id: nil, session_timeout: nil, start_time: nil, tunnel_url: nil, updated_at: nil, user_id: nil, ws_gpu: nil)
        @cost = cost
        @cost_item_title = cost_item_title
        @created_at = created_at
        @end_time = end_time
        @environment = environment
        @gpu = gpu
        @id = id
        @machine_id = machine_id
        @machine_version_id = machine_version_id
        @modal_function_id = modal_function_id
        @org_id = org_id
        @provider_type = provider_type
        @session_id = session_id
        @session_timeout = session_timeout
        @start_time = start_time
        @tunnel_url = tunnel_url
        @updated_at = updated_at
        @user_id = user_id
        @ws_gpu = ws_gpu
      end
    end
  end
end
