# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetWorkflowVersionVersionIdRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :version_id, ::String, { 'path_param': { 'field_name': 'version_id', 'style': 'simple', 'explode': false } }


      sig { params(version_id: ::String).void }
      def initialize(version_id: nil)
        @version_id = version_id
      end
    end
  end
end
