# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1MachinesMachineIdRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :machine_id, ::String, { 'path_param': { 'field_name': 'machine_id', 'style': 'simple', 'explode': false } }

      field :ext_urls, T.nilable(::String), { 'query_param': { 'field_name': 'extUrls', 'style': 'form', 'explode': true } }


      sig { params(machine_id: ::String, ext_urls: T.nilable(::String)).void }
      def initialize(machine_id: nil, ext_urls: nil)
        @machine_id = machine_id
        @ext_urls = ext_urls
      end
    end
  end
end
