# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1WorkflowsWorkflowIdOutputsRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :workflow_id, ::String, { 'path_param': { 'field_name': 'workflow_id', 'style': 'simple', 'explode': false } }

      field :page, T.nilable(::String), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }

      field :page_size, T.nilable(::String), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }

      field :run_origin, T.nilable(::OpenApiSDK::Operations::QueryParamRunOrigin), { 'query_param': { 'field_name': 'runOrigin', 'style': 'form', 'explode': true } }

      field :search, T.nilable(::String), { 'query_param': { 'field_name': 'search', 'style': 'form', 'explode': true } }


      sig { params(workflow_id: ::String, page: T.nilable(::String), page_size: T.nilable(::String), run_origin: T.nilable(::OpenApiSDK::Operations::QueryParamRunOrigin), search: T.nilable(::String)).void }
      def initialize(workflow_id: nil, page: nil, page_size: nil, run_origin: nil, search: nil)
        @workflow_id = workflow_id
        @page = page
        @page_size = page_size
        @run_origin = run_origin
        @search = search
      end
    end
  end
end
