# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetDeploymentIdInputsResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # Error when uploading the workflow
      field :object, T.nilable(::OpenApiSDK::Operations::GetDeploymentIdInputsResponseBody)
      # Invalid or expired token
      field :res, T.nilable(::String)
      # Retrieve the output
      field :response_bodies, T.nilable(T::Array[::OpenApiSDK::Operations::ResponseBody])


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, object: T.nilable(::OpenApiSDK::Operations::GetDeploymentIdInputsResponseBody), res: T.nilable(::String), response_bodies: T.nilable(T::Array[::OpenApiSDK::Operations::ResponseBody])).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, object: nil, res: nil, response_bodies: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @object = object
        @res = res
        @response_bodies = response_bodies
      end
    end
  end
end
