# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetDeploymentClassType < T::Enum
      enums do
        COMFY_UI_DEPLOY_EXTERNAL_TEXT = new('ComfyUIDeployExternalText')
        COMFY_UI_DEPLOY_EXTERNAL_TEXT_ANY = new('ComfyUIDeployExternalTextAny')
        COMFY_UI_DEPLOY_EXTERNAL_TEXT_SINGLE_LINE = new('ComfyUIDeployExternalTextSingleLine')
        COMFY_UI_DEPLOY_EXTERNAL_IMAGE = new('ComfyUIDeployExternalImage')
        COMFY_UI_DEPLOY_EXTERNAL_IMAGE_ALPHA = new('ComfyUIDeployExternalImageAlpha')
        COMFY_UI_DEPLOY_EXTERNAL_NUMBER = new('ComfyUIDeployExternalNumber')
        COMFY_UI_DEPLOY_EXTERNAL_NUMBER_INT = new('ComfyUIDeployExternalNumberInt')
        COMFY_UI_DEPLOY_EXTERNAL_LORA = new('ComfyUIDeployExternalLora')
        COMFY_UI_DEPLOY_EXTERNAL_CHECKPOINT = new('ComfyUIDeployExternalCheckpoint')
        COMFY_DEPLOY_WEBSCOKET_IMAGE_INPUT = new('ComfyDeployWebscoketImageInput')
        COMFY_UI_DEPLOY_EXTERNAL_IMAGE_BATCH = new('ComfyUIDeployExternalImageBatch')
        COMFY_UI_DEPLOY_EXTERNAL_VIDEO = new('ComfyUIDeployExternalVideo')
        COMFY_UI_DEPLOY_EXTERNAL_BOOLEAN = new('ComfyUIDeployExternalBoolean')
        COMFY_UI_DEPLOY_EXTERNAL_NUMBER_SLIDER = new('ComfyUIDeployExternalNumberSlider')
        COMFY_UI_DEPLOY_EXTERNAL_NUMBER_SLIDER_INT = new('ComfyUIDeployExternalNumberSliderInt')
        COMFY_UI_DEPLOY_EXTERNAL_ENUM = new('ComfyUIDeployExternalEnum')
        COMFY_UI_DEPLOY_EXTERNAL_COLOR = new('ComfyUIDeployExternalColor')
      end
    end
  end
end
