# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1MachinesRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :fields_, T.nilable(::OpenApiSDK::Operations::Fields), { 'query_param': { 'field_name': 'fields', 'style': 'form', 'explode': true } }

      field :page, T.nilable(::String), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }

      field :page_size, T.nilable(::String), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }


      sig { params(fields_: T.nilable(::OpenApiSDK::Operations::Fields), page: T.nilable(::String), page_size: T.nilable(::String)).void }
      def initialize(fields_: nil, page: nil, page_size: nil)
        @fields_ = fields_
        @page = page
        @page_size = page_size
      end
    end
  end
end
