# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetMachineMachineIdEventsEnvironment < T::Enum
      enums do
        STAGING = new('staging')
        PREVIEW = new('preview')
        PRODUCTION = new('production')
        PUBLIC_SHARE = new('public-share')
        PRIVATE_SHARE = new('private-share')
      end
    end
  end
end
