# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetUploadUrlRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :file_size, ::String, { 'query_param': { 'field_name': 'file_size', 'style': 'form', 'explode': true } }

      field :type, ::OpenApiSDK::Operations::Type, { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }

      field :file_extension, T.nilable(::String), { 'query_param': { 'field_name': 'file_extension', 'style': 'form', 'explode': true } }


      sig { params(file_size: ::String, type: ::OpenApiSDK::Operations::Type, file_extension: T.nilable(::String)).void }
      def initialize(file_size: nil, type: nil, file_extension: nil)
        @file_size = file_size
        @type = type
        @file_extension = file_extension
      end
    end
  end
end
