# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Specific workflow retrieved successfully
    class GetV1WorkflowsWorkflowIdResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :selected_machine_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('selected_machine_id') } }

      field :updated_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at') } }

      field :user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }

      field :versions, T::Array[::OpenApiSDK::Operations::GetV1WorkflowsWorkflowIdVersions], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('versions') } }

      field :org_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('org_id') } }


      sig { params(created_at: ::String, id: ::String, name: ::String, selected_machine_id: ::String, updated_at: ::String, user_id: ::String, versions: T::Array[::OpenApiSDK::Operations::GetV1WorkflowsWorkflowIdVersions], org_id: T.nilable(::String)).void }
      def initialize(created_at: nil, id: nil, name: nil, selected_machine_id: nil, updated_at: nil, user_id: nil, versions: nil, org_id: nil)
        @created_at = created_at
        @id = id
        @name = name
        @selected_machine_id = selected_machine_id
        @updated_at = updated_at
        @user_id = user_id
        @versions = versions
        @org_id = org_id
      end
    end
  end
end
