# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Specific machine retrieved successfully
    class GetV1MachinesMachineIdResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :message, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('message') } }

      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :status, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status') } }

      field :type, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }

      field :updated_at, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at') } }


      sig { params(created_at: T.nilable(::String), id: T.nilable(::String), message: T.nilable(::String), name: T.nilable(::String), status: T.nilable(::String), type: T.nilable(::String), updated_at: T.nilable(::String)).void }
      def initialize(created_at: nil, id: nil, message: nil, name: nil, status: nil, type: nil, updated_at: nil)
        @created_at = created_at
        @id = id
        @message = message
        @name = name
        @status = status
        @type = type
        @updated_at = updated_at
      end
    end
  end
end
