# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetUploadUrlRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :file_size, ::String, { 'query_param': { 'field_name': 'file_size', 'style': 'form', 'explode': true } }

      field :type, ::OpenApiSDK::Operations::Type, { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }


      sig { params(file_size: ::String, type: ::OpenApiSDK::Operations::Type).void }
      def initialize(file_size: nil, type: nil)
        @file_size = file_size
        @type = type
      end
    end
  end
end
