# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Retrieve the output
    class GetWorkflowVersionVersionIdResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :comment, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('comment') } }

      field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :machine_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machine_id') } }

      field :machine_version_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machine_version_id') } }

      field :updated_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at') } }

      field :user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }

      field :version, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('version') } }

      field :workflow_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow_id') } }

      field :dependencies, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('dependencies') } }

      field :snapshot, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('snapshot') } }

      field :workflow, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow') } }

      field :workflow_api, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow_api') } }


      sig { params(comment: ::String, created_at: ::String, id: ::String, machine_id: ::String, machine_version_id: ::String, updated_at: ::String, user_id: ::String, version: ::Float, workflow_id: ::String, dependencies: T.nilable(::Object), snapshot: T.nilable(::Object), workflow: T.nilable(::Object), workflow_api: T.nilable(::Object)).void }
      def initialize(comment: nil, created_at: nil, id: nil, machine_id: nil, machine_version_id: nil, updated_at: nil, user_id: nil, version: nil, workflow_id: nil, dependencies: nil, snapshot: nil, workflow: nil, workflow_api: nil)
        @comment = comment
        @created_at = created_at
        @id = id
        @machine_id = machine_id
        @machine_version_id = machine_version_id
        @updated_at = updated_at
        @user_id = user_id
        @version = version
        @workflow_id = workflow_id
        @dependencies = dependencies
        @snapshot = snapshot
        @workflow = workflow
        @workflow_api = workflow_api
      end
    end
  end
end
