# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # The returned API Key
    class GetAuthResponseRequestIdResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :api_key, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('api_key') } }

      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }


      sig { params(api_key: ::String, name: ::String).void }
      def initialize(api_key: nil, name: nil)
        @api_key = api_key
        @name = name
      end
    end
  end
end
