# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetV1WorkflowsWorkflowIdVersions < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :comment, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('comment') } }

      field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :dependencies, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('dependencies') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :snapshot, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('snapshot') } }

      field :updated_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at') } }

      field :version, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('version') } }

      field :workflow_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow_id') } }

      field :workflow, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow') } }

      field :workflow_api, T.nilable(::Object), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow_api') } }


      sig { params(comment: ::String, created_at: ::String, dependencies: ::String, id: ::String, snapshot: ::String, updated_at: ::String, version: ::Float, workflow_id: ::String, workflow: T.nilable(::Object), workflow_api: T.nilable(::Object)).void }
      def initialize(comment: nil, created_at: nil, dependencies: nil, id: nil, snapshot: nil, updated_at: nil, version: nil, workflow_id: nil, workflow: nil, workflow_api: nil)
        @comment = comment
        @created_at = created_at
        @dependencies = dependencies
        @id = id
        @snapshot = snapshot
        @updated_at = updated_at
        @version = version
        @workflow_id = workflow_id
        @workflow = workflow
        @workflow_api = workflow_api
      end
    end
  end
end
