# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetDeploymentRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :environment, T.nilable(::OpenApiSDK::Operations::Environment), { 'query_param': { 'field_name': 'environment', 'style': 'form', 'explode': true } }


      sig { params(environment: T.nilable(::OpenApiSDK::Operations::Environment)).void }
      def initialize(environment: nil)
        @environment = environment
      end
    end
  end
end
