# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Machines retrieved successfully
    class GetV1MachinesResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :machines, T::Array[::OpenApiSDK::Operations::Machines], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machines') } }

      field :total, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total') } }


      sig { params(machines: T::Array[::OpenApiSDK::Operations::Machines], total: ::Float).void }
      def initialize(machines: nil, total: nil)
        @machines = machines
        @total = total
      end
    end
  end
end
