# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GitCustomNodes < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :disabled, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('disabled') } }

      field :hash, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('hash') } }


      sig { params(disabled: T::Boolean, hash: ::String).void }
      def initialize(disabled: nil, hash: nil)
        @disabled = disabled
        @hash = hash
      end
    end
  end
end
