# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GpuProvider < T::Enum
      enums do
        MODAL = new('modal')
        RUNPOD = new('runpod')
      end
    end

  end
end
