# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GpuType < T::Enum
      enums do
        T4 = new('T4')
        L4 = new('L4')
        A10_G = new('A10G')
        A100 = new('A100')
        H100 = new('H100')
      end
    end

  end
end
