# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class MachineType < T::Enum
      enums do
        CLASSIC = new('classic')
        RUNPOD_SERVERLESS = new('runpod-serverless')
        MODAL_SERVERLESS = new('modal-serverless')
        COMFY_DEPLOY_SERVERLESS = new('comfy-deploy-serverless')
        WORKSPACE = new('workspace')
        WORKSPACE_V2 = new('workspace-v2')
      end
    end
  end
end
