# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Outputs < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :data, ::OpenApiSDK::Operations::Data, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }


      sig { params(data: ::OpenApiSDK::Operations::Data).void }
      def initialize(data: nil)
        @data = data
      end
    end
  end
end
