# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Create short lived machine endpoint
    class PostMachineEndpointResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :gpu, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('gpu') } }

      field :url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url') } }


      sig { params(gpu: ::String, url: ::String).void }
      def initialize(gpu: nil, url: nil)
        @gpu = gpu
        @url = url
      end
    end
  end
end
