# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostV1MachinesStatus < T::Enum
      enums do
        BUILDING = new('building')
      end
    end

  end
end
