# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostV1MachinesGpu < T::Enum
      enums do
        A10_G = new('A10G')
      end
    end
  end
end
