# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostEndGpuEventRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :event_type, ::OpenApiSDK::Operations::PostEndGpuEventEventType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('eventType'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::PostEndGpuEventEventType, false) } }

      field :event_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('event_id') } }


      sig { params(event_type: ::OpenApiSDK::Operations::PostEndGpuEventEventType, event_id: T.nilable(::String)).void }
      def initialize(event_type: nil, event_id: nil)
        @event_type = event_type
        @event_id = event_id
      end
    end
  end
end
