# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostV1MachinesType < T::Enum
      enums do
        COMFY_DEPLOY_SERVERLESS = new('comfy-deploy-serverless')
      end
    end

  end
end
