# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class PostMachineEndpointRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :machine_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('machine_id') } }

      field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


      sig { params(machine_id: ::String, type: ::String).void }
      def initialize(machine_id: nil, type: nil)
        @machine_id = machine_id
        @type = type
      end
    end
  end
end
