# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class ResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :class_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('class_type') } }

      field :default_value, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('default_value') } }

      field :input_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('input_id') } }

      field :max_value, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_value') } }

      field :min_value, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('min_value') } }


      sig { params(class_type: ::String, default_value: ::String, input_id: ::String, max_value: ::Float, min_value: ::Float).void }
      def initialize(class_type: nil, default_value: nil, input_id: nil, max_value: nil, min_value: nil)
        @class_type = class_type
        @default_value = default_value
        @input_id = input_id
        @max_value = max_value
        @min_value = min_value
      end
    end
  end
end
