# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Snapshot < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :comfyui, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('comfyui') } }

      field :file_custom_nodes, T::Array[::Object], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_custom_nodes') } }

      field :git_custom_nodes, T::Hash[Symbol, ::OpenApiSDK::Operations::GitCustomNodes], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('git_custom_nodes') } }


      sig { params(comfyui: ::String, file_custom_nodes: T::Array[::Object], git_custom_nodes: T::Hash[Symbol, ::OpenApiSDK::Operations::GitCustomNodes]).void }
      def initialize(comfyui: nil, file_custom_nodes: nil, git_custom_nodes: nil)
        @comfyui = comfyui
        @file_custom_nodes = file_custom_nodes
        @git_custom_nodes = git_custom_nodes
      end
    end
  end
end
