# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Status
    class Status < T::Enum
      enums do
        RUNNING = new('running')
        COMPLETED = new('completed')
      end
    end
  end
end
