# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class WebhookStatus < T::Enum
      enums do
        SUCCESS = new('success')
        FAILED = new('failed')
        NOT_STARTED = new('not-started')
        RUNNING = new('running')
      end
    end
  end
end
