# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class WsGpuType < T::Enum
      enums do
        FOUR_THOUSAND_AND_NINETY = new('4090')
      end
    end
  end
end
